package com.netposa.bootpro.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.netposa.bootpro.pojo.Content;
import com.netposa.bootpro.pojo.ContentExample;

public interface ContentMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    int countByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    int deleteByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    int insert(Content record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    int insertSelective(Content record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    List<Content> selectByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    Content selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") Content record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    int updateByExample(@Param("record") Content record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    int updateByPrimaryKeySelective(Content record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    int updateByPrimaryKey(Content record);

    Integer getMax();
}