package com.netposa.bootpro.pojo;

public class Content {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column content.id
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column content.content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column content.id
     * @return  the value of content.id
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column content.id
     * @param id  the value for content.id
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column content.content
     * @return  the value of content.content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column content.content
     * @param content  the value for content.content
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}