package com.netposa.bootpro.pojo;

import java.util.Date;

public class User {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private String id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private String password;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.salt
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private String salt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.mobilephone
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private String mobilephone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_time
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
     * @return  the value of user.id
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
     * @param id  the value for user.id
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
     * @return  the value of user.username
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
     * @param username  the value for user.username
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
     * @return  the value of user.password
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
     * @param password  the value for user.password
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.salt
     * @return  the value of user.salt
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.salt
     * @param salt  the value for user.salt
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
     * @return  the value of user.name
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
     * @param name  the value for user.name
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.mobilephone
     * @return  the value of user.mobilephone
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.mobilephone
     * @param mobilephone  the value for user.mobilephone
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
     * @return  the value of user.create_time
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
     * @param createTime  the value for user.create_time
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column user.update_time
     * @return  the value of user.update_time
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column user.update_time
     * @param updateTime  the value for user.update_time
     * @mbggenerated  Thu Mar 30 09:40:24 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}